
addpath(genpath('C:\Users\dibg280\Documents\MATLAB'));

set(0, 'DefaultFigureColor', 'White',...    
'DefaultAxesFontUnits', 'points', ...
'DefaultAxesFontSize', 30, ...
'DefaultAxesFontWeight', 'bold', ...
'DefaultLineColor', 'Red', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineLineWidth', 4, ...
'DefaultLineMarkerSize', 15, ...
'DefaultAxesXGrid', 'on', ...
'DefaultAxesYGrid', 'on', ...
'DefaultAxesZGrid', 'on');
